---
title: "graficas"
author: "jhon"
date: "29/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

# instalacion de librearias

library(tidyverse)
library(readxl)
library(dplyr)


```

```{r}
# Lectura de la base de datos 

base <- read_excel("Respuestas trabajo estadistica.xlsx")

# copia 
base2 <- base


```


```{r}


# primera grafca

grafica1 <- base2 %>% 
  select(Género, Aleatoriedad) %>% 
  mutate(Género = str_replace(Género, "F", "Femenino")) %>%
  mutate(Género = str_replace(Género, "M", "Masculino")) %>% 
  group_by(Aleatoriedad, Género) %>% 
  summarise(Cantidad = n())

ggplot(grafica1, aes(x =Género,  y = Cantidad, group = Aleatoriedad, fill = Género))+
  geom_bar(stat = "identity")+
  facet_wrap(~Aleatoriedad, scales = "free_y")
```


```{r}
Grafica2 <- base2 %>% 
  select(`Creencia con respecto al destino o a la suerte`, Aleatoriedad) %>% 
  group_by(Aleatoriedad, `Creencia con respecto al destino o a la suerte`) %>% 
  summarise(Cantidad = n())

ggplot(Grafica2, aes(x =`Creencia con respecto al destino o a la suerte`,  y = Cantidad, group = Aleatoriedad, fill = `Creencia con respecto al destino o a la suerte`))+
  geom_bar(stat = "identity")+
  facet_wrap(~Aleatoriedad, scales = "free_y")
```
```{r}
Grafica3 <- base2 %>% 
  select(`Nivel de estudio`, Aleatoriedad) %>% 
  group_by(Aleatoriedad, `Nivel de estudio`) %>% 
  summarise(Cantidad = n())

ggplot(Grafica3, aes(x =`Nivel de estudio`,  y = Cantidad, group = Aleatoriedad, fill = `Nivel de estudio`))+
  geom_bar(stat = "identity")+
  facet_wrap(~Aleatoriedad, scales = "free_y")
```
```{r}
Grafica4 <- base2 %>% 
  select(`Inclinación al área del conocimiento`, Aleatoriedad) %>% 
  group_by(Aleatoriedad, `Inclinación al área del conocimiento`) %>% 
  summarise(Cantidad = n())

ggplot(Grafica4, aes(x =`Inclinación al área del conocimiento`,  y = Cantidad, group = Aleatoriedad, fill = `Inclinación al área del conocimiento`))+
  geom_bar(stat = "identity")+
  facet_wrap(~Aleatoriedad, scales = "free_y")+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```
```{r}
Grafica5 <- base2 %>% 
  select(Edad, Aleatoriedad) %>% 
  mutate(Edad = as.numeric(Edad)) %>% 
  filter(Edad %in% c(15:25)) %>% 
  group_by(Aleatoriedad, Edad) %>% 
  summarise(Cantidad = n())

total01 <- bind_rows(Grafica5 %>% rownames_to_column())


a <- total01 %>% 
  select(Aleatoriedad, Cantidad) %>% 
  filter(Aleatoriedad %in% "Grupal") %>% 
  group_by(Aleatoriedad) %>% 
  summarise(j = sum(Cantidad))

b <- total01 %>% 
  select(Aleatoriedad, Cantidad) %>% 
  filter(Aleatoriedad %in% "Sistemático") %>% 
  group_by(Aleatoriedad) %>% 
  summarise(j = sum(Cantidad))

c <- total01 %>% 
  select(Aleatoriedad, Cantidad) %>% 
  filter(Aleatoriedad %in% "Aleatorio") %>% 
  group_by(Aleatoriedad) %>% 
  summarise(j = sum(Cantidad))

j = rbind(a,b,c)

v <- as.data.frame(t(j[,-1]))
t<- bind_rows(v %>% rownames_to_column())


t2<- t%>%
  dplyr::rename("Grupal"=V1,Sistemático=V2,"Intervalo"=rowname, Aleatorio = V3)

t2 <- t2 %>% 
  mutate(Intervalo = str_replace(Intervalo, "j", "[15;25]"))




```
```{r}
Grafica5.1 <- base2 %>% 
  select(Edad, Aleatoriedad) %>% 
  mutate(Edad = as.numeric(Edad)) %>% 
  filter(Edad %in% c(25:40)) %>% 
  group_by(Aleatoriedad, Edad) %>% 
  summarise(Cantidad = n())

total011 <- bind_rows(Grafica5.1 %>% rownames_to_column())


a1 <- total011 %>% 
  select(Aleatoriedad, Cantidad) %>% 
  filter(Aleatoriedad %in% "Grupal") %>% 
  group_by(Aleatoriedad) %>% 
  summarise(j = sum(Cantidad))

b1 <- total011 %>% 
  select(Aleatoriedad, Cantidad) %>% 
  filter(Aleatoriedad %in% "Sistemático") %>% 
  group_by(Aleatoriedad) %>% 
  summarise(j = sum(Cantidad))

c1 <- total011 %>% 
  select(Aleatoriedad, Cantidad) %>% 
  filter(Aleatoriedad %in% "Aleatorio") %>% 
  group_by(Aleatoriedad) %>% 
  summarise(j = sum(Cantidad))

j1 = rbind(a1,b1,c1)

p <- as.data.frame(t(j1[,-1]))
y<- bind_rows(p %>% rownames_to_column())


y<- y%>%
  dplyr::rename("Grupal"=V1,Sistemático=V2,"Intervalo"=rowname, Aleatorio = V3)

y<- y %>% 
  mutate(Intervalo = str_replace(Intervalo, "j", "[25;40]"))


```
```{r}
Grafica5.2 <- base2 %>% 
  select(Edad, Aleatoriedad) %>% 
  mutate(Edad = as.numeric(Edad)) %>% 
  filter(Edad %in% c(40:60)) %>% 
  group_by(Aleatoriedad, Edad) %>% 
  summarise(Cantidad = n())

total0111 <- bind_rows(Grafica5.2 %>% rownames_to_column())


a2 <- total0111 %>% 
  select(Aleatoriedad, Cantidad) %>% 
  filter(Aleatoriedad %in% "Grupal") %>% 
  group_by(Aleatoriedad) %>% 
  summarise(j = sum(Cantidad))

b2 <- total0111 %>% 
  select(Aleatoriedad, Cantidad) %>% 
  filter(Aleatoriedad %in% "Sistemático") %>% 
  group_by(Aleatoriedad) %>% 
  summarise(j = sum(Cantidad))

c2 <- total0111 %>% 
  select(Aleatoriedad, Cantidad) %>% 
  filter(Aleatoriedad %in% "Aleatorio") %>% 
  group_by(Aleatoriedad) %>% 
  summarise(j = sum(Cantidad))

j2 = rbind(a2,b2,c2)

p1 <- as.data.frame(t(j2[,-1]))
y1<- bind_rows(p1 %>% rownames_to_column())


y1<- y1%>%
  dplyr::rename("Grupal"=V1,Sistemático=V2,"Intervalo"=rowname, Aleatorio = V3)

y1<- y1 %>% 
  mutate(Intervalo = str_replace(Intervalo, "j", "[40;60]"))


```


```{r}
ultima <- rbind(t2,y, y1)

q <- as.data.frame(t(ultima[,-1]))

q11<- q%>%
  dplyr::rename("[15:25]"=V1,"[25:40]"=V2, "[40:60]" = V3)

q2 <- t(q11)

```

```{r}

barplot(q2, col = c("#999999", "#E69F00", "#56B4E9"),
        legend = rownames(q2),
        beside = TRUE)


```

